# Generated by Django 3.1.4 on 2022-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=20, verbose_name='教室名稱')),
                ('roomId', models.CharField(max_length=10, verbose_name='教室編號')),
                ('roomStatus', models.IntegerField(choices=[(0, '無法預約'), (1, '開放預約')], default=1, verbose_name='狀態')),
            ],
        ),
    ]
