# Generated by Django 3.1.4 on 2022-04-11 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtype', models.IntegerField(choices=[(0, '單筆預約'), (1, '多筆預約')], default=0, verbose_name='預約之類型')),
                ('logDate', models.DateField(verbose_name='預約日期')),
                ('logStart', models.TimeField(verbose_name='開始時間')),
                ('logEnd', models.TimeField(verbose_name='結束時間')),
                ('logPurpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('logRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('logUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
