# Generated by Django 3.1.4 on 2022-04-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='logtype',
        ),
    ]
